version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - biteBusters:/var/lib/postgresql/data
      - ./ProjectSourceCode/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /home/node/biteBusters/ProjectSourceCode
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/biteBusters
    command: 'npm start'

volumes:
  biteBusters:
